# Generated by Django 6.0 on 2026-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In_progress'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=15),
        ),
    ]
