# Generated by Django 6.0 on 2026-01-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
